- hosts: localhost
  pre_tasks:
    - name: Update cache
      become: true
      apt:
        update_cache: true
      tags:
        - zsh
  tasks:
    - include: tasks/zsh.yml
    - include: tasks/node.yml
    - include: tasks/core.yml

