- name: Install Neovim build Prerequisites
  become: true
  apt:
    name:
      - ninja-build 
      - gettext 
      - libtool 
      - libtool-bin 
      - autoconf 
      - automake 
      - cmake 
      - g++ 
      - pkg-config 
      - unzip 
      - curl 
      - doxygen
  tags: 
    - neovim
- name: Clone Neovim
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim
    dest: ~/neovim
  tags:
    - neovim

- name: Build Neovim
  shell: cd ~/neovim && make CMAKE_BUILD_TYPE=Release 
  tags:
    - neovim

- name: Install Neovim
  become: true
  shell: cd {{ lookup('env', 'HOME')}}/neovim && make install
  tags:
    - neovim

- name: Copy configuration
  ansible.builtin.copy:
    src: ~/config/dotfiles/neovim/
    dest: ~/.config/nvim/
  tags:
    - neovim
# Copy dotfile config to proper location, install packer, Run packer sync automatically?, 

