- name: Install zsh
  apt: name=zsh
  tags:
    - zsh
- name: Change shell
  shell: chsh -s `which zsh`
- name: Install zsh autosuggestions plugin 
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.zsh/zsh-autosuggestions
  tags:
    - zsh
- name: Clone dotfiles repo
  ansible.builtin.git:
    repo: https://github.com/sagarthomas/dotfiles.git
    dest: ~/dotfiles
  tags:
    - zsh
- name: Clone Pure zsh theme
  ansible.builtin.git: 
    repo: https://github.com/sindresorhus/pure.git
    dest: ~/.zsh/pure
  tags:
    - zsh
- name: Clone zsh sytax highlighting
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.zsh/zsh-syntax-highlighting
  tags:
    - zsh
- name: Set up .zshrc
  shell: cp ~/dotfiles/.zshrc ~/
  tags:
    - zsh
